name: HydraSense CI/CD Pipeline

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  
jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout action
        uses: actions/checkout@v3
      
      # Setup python
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.9'
      
      # Execute train pipeline
      - name: Train pipeline execution
        run: |
          pip install -r requirements.txt
          python src/pipeline/train_pipeline.py
      
      # Docker Login
      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      # ML-service image push
      - name: ML-service image push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./ml-services/Dockerfile.ml
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/hydrasense-ml-service:latest
      
      # Frontend image push
      - name: Frontend image push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./frontend/Dockerfile.frontend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/hydrasense-frontend:latest
      
      # Backend image push
      - name: Backend image push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./backend/Dockerfile.backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/hydrasense-backend:latest

  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    needs: [build-and-push-images]
    steps:
      - name: Deploy Backend
        run: curl ${{ secrets.RENDER_BACKEND_URL }}

      - name: Deploy Frontend
        run: curl ${{ secrets.RENDER_FRONTEND_URL }}
        
      - name: Deploy ML Service
        run: curl ${{ secrets.RENDER_ML_URL }}