name: HydraSense CI/CD Pipeline

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  
jobs:
  build-and-push-images:
    name: Build and Push images to Docker HUB
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout code
      - name: Checkout action
        uses: actions/checkout@v3
      
      # 2. Setup python
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.9'
      
      # 3. Train Model
      - name: Train pipeline execution
        run: |
          pip install -r requirements.txt
          python src/pipeline/train_pipeline.py
      
      # 4. Login to Docker
      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      # 5. Build ML Service
      - name: ML-service image push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./ml-services/Dockerfile.ml
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/hydrasense-ml-service:latest
      
      # 6. Build Frontend
      - name: Frontend image push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./frontend/Dockerfile.frontend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/hydrasense-frontend:latest
          build-args: |
            REACT_APP_BACKEND_URL=${{ secrets.REACT_APP_BACKEND_URL }}
            REACT_APP_WEATHER_API_KEY=${{ secrets.REACT_APP_WEATHER_API_KEY }}
      
      # 7. Build Backend
      - name: Backend image push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./backend/Dockerfile.backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/hydrasense-backend:latest

  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    needs: [build-and-push-images]
    steps:
      - name: Deploy Backend
        run: curl -X POST -f -v ${{ secrets.RENDER_BACKEND_URL }}

      - name: Deploy Frontend
        run: curl -X POST -f -v ${{ secrets.RENDER_FRONTEND_URL }}
        
      - name: Deploy ML Service
        run: curl -X POST -f -v ${{ secrets.RENDER_ML_URL }}